### ISSUE TITLE
Rocking !!!!!

### ISSUE THREAD

**Issue by swagkarna** [sulanmehmetsirin/RaptorWebPanel#3]
Awesome Bro..This Repo is Just Awesome....This  is going to be a most trending repo in 2021...Hats off to you for creating this repo......I have used this Repo its working good but app crashes sometimes.....

**Comment by graysuit** [comment]
@swagkarna 
You better use `LOGCAT` tool and capture the errors at time when app crash
`LOGCAT` available for `android studio` or `visual studio`.
